FROM python:3.11-slim
RUN apt-get update && apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install flask pillow pytesseract
COPY app.py /app/app.py

EXPOSE 5000
CMD ["python", "app.py"]
